---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # Don't do the . paths, below; fakes out chef-zero
  #data_bags_path: .
  encrypted_data_bag_secret_key_path: ./.chef/insecure_encrypted_data_bag_secret
  #environments_path: .
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    driver:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
      network:
        - ["private_network", {ip: "192.168.43.6"}]
suites:
  - name: default
    run_list: recipe[rails_infrastructure]
    provisioner:
      client_rb:
        environment: test
    attributes:
